import { useState, useEffect } from 'react';
import { getMissionKingBadge } from '../utils/badgeUtils';
import { generateRandomMission } from '../utils/missionGenerator';

import {
  Container,
  Grid,
  Paper,
  Typography,
  Box,
  Button,
  Card,
  CardContent,
  CardActions,
  LinearProgress,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Alert,
  Tooltip,
} from '@mui/material';
import {
  EmojiEvents as EmojiEventsIcon,
  Add as AddIcon,
  CheckCircle as CheckCircleIcon,
  Info as InfoIcon,
} from '@mui/icons-material';
import { findChildById, updateChild, getChildrenByParent, updateChild as updateChildData } from '../utils/localData';
import { useLocation } from 'react-router-dom';

function Missions() {
  const location = useLocation();
  const user = JSON.parse(sessionStorage.getItem('user'));
  const isParent = user?.role === 'parent';
  const [missions, setMissions] = useState([]);
  const [openDialog, setOpenDialog] = useState(false);
  const [openDetailDialog, setOpenDetailDialog] = useState(false);
  const [newMission, setNewMission] = useState({
    title: '',
    description: '',
    reward: '',
    deadline: '',
  });
  const [selectedMission, setSelectedMission] = useState(null);
  const [error, setError] = useState('');

  //미션 없는 경우 자동 생성 
  useEffect(() => {
    const hasGenerated = sessionStorage.getItem('missionAutoGenerated');
    if (!isParent && !hasGenerated && missions.length === 0) {
      const child = findChildById(user.id);
      const newMission = generateRandomMission();
      const updated = { ...child };
      updated.missions = [...(child.missions || []), newMission];
      updateChild(updated);
      setMissions(updated.missions);
      sessionStorage.setItem('missionAutoGenerated', 'true');
    }
  }, [isParent, user.id]);  // setMissions에 의한 무한 루프 방지
  
  // 미션 불러오기
  useEffect(() => {
    if (isParent) {
      const children = getChildrenByParent(user.id);
      setMissions(children.flatMap(c => (c.missions || []).map(m => ({ ...m, childName: c.name, childId: c.id }))));
    } else {
      const child = findChildById(user.id);
      setMissions(child?.missions || []);
    }
  }, [user, location.pathname]);

  // 미션 추가
  const handleSubmitMission = () => {
    setError('');
    if (!newMission.title || !newMission.description || !newMission.reward || !newMission.deadline) {
      setError('모든 필드를 입력해주세요.');
      return;
    }
    if (isParent) {
      const children = getChildrenByParent(user.id);
      children.forEach(child => {
        const updated = { ...child };
        updated.missions = [
          ...(updated.missions || []),
          {
            id: Date.now() + Math.random(),
            ...newMission,
            progress: 0,
            status: '진행중',
            createdAt: new Date().toISOString().slice(0, 10),
          },
        ];
        updateChildData(updated);
      });
      // 미션 목록 즉시 갱신
      const updatedChildren = getChildrenByParent(user.id);
      setMissions(updatedChildren.flatMap(c => (c.missions || []).map(m => ({ ...m, childName: c.name, childId: c.id }))));
    } else {
      const child = findChildById(user.id);
      const updated = { ...child };
      updated.missions = [
        ...(updated.missions || []),
        {
          id: Date.now(),
          ...newMission,
          progress: 0,
          status: '진행중',
          createdAt: new Date().toISOString().slice(0, 10),
        },
      ];
      updateChild(updated);
      setMissions(updated.missions); // 즉시 갱신
    }
    setOpenDialog(false);
    setNewMission({ title: '', description: '', reward: '', deadline: '' });
  };

  // 미션 완료
  const handleCompleteMission = (mission) => {
  if (isParent) return;
  const child = findChildById(user.id);
  const updated = { ...child };
  updated.missions = (updated.missions || []).map(m =>
    m.id === mission.id ? { ...m, status: '완료', progress: 100, completedAt: new Date().toISOString().slice(0, 10) } : m
  );
  updated.points = (updated.points || 0) + Number(mission.reward || 0);

  // 🏅 뱃지 계산 추가
  const badge = getMissionKingBadge(updated.missions);
  if (!updated.badges) updated.badges = {};
  if (badge) {
    updated.badges['미션왕'] = badge;
  }

  updateChild(updated);
  setMissions(updated.missions); // 즉시 갱신
  setOpenDetailDialog(false);
};


  // 미션 상세보기
  const handleOpenDetail = (mission) => {
    setSelectedMission(mission);
    setOpenDetailDialog(true);
  };

  return (
    <Container maxWidth="lg" sx={{ pt: '64px', mt: 2, mb: 2, minHeight: '70vh' }}>
      <Grid container spacing={1} alignItems="flex-start" justifyContent="flex-start">
        {/* Header */}
        <Grid item xs={12}>
          <Paper sx={{ p: 1, display: 'flex', justifyContent: 'space-between', alignItems: 'center', boxShadow: 1, borderRadius: 1 }}>
            <Typography variant="h4" component="h1">
              미션 & 챌린지
            </Typography>
            <Button
              variant="contained"
              color="primary"
              startIcon={<AddIcon />}
              onClick={() => setOpenDialog(true)}
              sx={{ borderRadius: 2, fontWeight: 600 }}
            >
              새 미션 만들기
            </Button>
          </Paper>
        </Grid>
        {/* Missions List */}
        <Grid item xs={12}>
          <Grid container spacing={1} alignItems="flex-start" justifyContent="flex-start">
            {missions.length > 0 ? missions.map((mission) => (
              <Grid item xs={12} md={6} lg={4} key={mission.id} sx={{ display: 'flex' }}>
                <Card sx={{ boxShadow: 1, flex: 1, display: 'flex', flexDirection: 'column', minHeight: 80, borderRadius: 1, transition: 'box-shadow 0.2s', '&:hover': { boxShadow: 4 } }}>
                  <CardContent sx={{ flexGrow: 1 }}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
                      <Typography variant="h6" component="div">
                        {mission.title}
                      </Typography>
                      <Chip
                        label={mission.status}
                        color={mission.status === '완료' ? 'success' : 'primary'}
                        size="small"
                        sx={{ ml: 1, borderRadius: 1 }}
                      />
                    </Box>
                    <Typography color="text.secondary" gutterBottom>
                      {mission.description}
                    </Typography>
                    {isParent && mission.childName && (
                      <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                        대상: {mission.childName}
                      </Typography>
                    )}
                    <Box sx={{ mt: 2 }}>
                      <Typography variant="body2" color="text.secondary">
                        보상: {mission.reward?.toLocaleString() || 0}원
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        마감일: {mission.deadline}
                      </Typography>
                    </Box>
                    <Box sx={{ mt: 2 }}>
                      <LinearProgress
                        variant="determinate"
                        value={mission.progress}
                        sx={{ height: 8, borderRadius: 4 }}
                      />
                      <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
                        진행률: {mission.progress}%
                      </Typography>
                    </Box>
                  </CardContent>
                  <CardActions>
                    <Button size="small" onClick={() => handleOpenDetail(mission)} startIcon={<InfoIcon />}>상세보기</Button>
                    {!isParent && mission.status === '진행중' && (
                      <Button size="small" color="success" startIcon={<CheckCircleIcon />} onClick={() => handleCompleteMission(mission)}>
                        완료하기
                      </Button>
                    )}
                  </CardActions>
                </Card>
              </Grid>
            )) : (
              <Grid item xs={12} sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: 60 }}>
                <Paper sx={{ p: 1, width: '100%', textAlign: 'center', boxShadow: 0, background: 'transparent', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Typography color="text.secondary">미션이 없습니다.</Typography>
                </Paper>
              </Grid>
            )}
          </Grid>
        </Grid>
      </Grid>
      {/* New Mission Dialog */}
      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle>새 미션 만들기</DialogTitle>
        <DialogContent>
          {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
          <Box sx={{ mt: 2 }}>
            <TextField
              fullWidth
              label="미션 제목"
              name="title"
              value={newMission.title}
              onChange={e => setNewMission(f => ({ ...f, title: e.target.value }))}
              margin="normal"
              required
            />
            <TextField
              fullWidth
              label="미션 설명"
              name="description"
              value={newMission.description}
              onChange={e => setNewMission(f => ({ ...f, description: e.target.value }))}
              margin="normal"
              multiline
              rows={3}
              required
            />
            <TextField
              fullWidth
              label="보상 금액"
              name="reward"
              type="number"
              value={newMission.reward}
              onChange={e => setNewMission(f => ({ ...f, reward: e.target.value }))}
              margin="normal"
              required
            />
            <TextField
              fullWidth
              label="마감일"
              name="deadline"
              type="date"
              value={newMission.deadline}
              onChange={e => setNewMission(f => ({ ...f, deadline: e.target.value }))}
              margin="normal"
              required
              InputLabelProps={{ shrink: true }}
            />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>취소</Button>
          <Button
            onClick={handleSubmitMission}
            variant="contained"
            color="primary"
            disabled={!newMission.title || !newMission.description || !newMission.reward || !newMission.deadline}
          >
            만들기
          </Button>
        </DialogActions>
      </Dialog>
      {/* Mission Detail Dialog */}
      <Dialog open={openDetailDialog} onClose={() => setOpenDetailDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle>미션 상세 정보</DialogTitle>
        <DialogContent>
          {selectedMission && (
            <Box>
              <Typography variant="h6">{selectedMission.title}</Typography>
              <Typography color="text.secondary" sx={{ mb: 1 }}>{selectedMission.description}</Typography>
              <Typography>보상: {selectedMission.reward?.toLocaleString() || 0}원</Typography>
              <Typography>마감일: {selectedMission.deadline}</Typography>
              <Typography>상태: {selectedMission.status}</Typography>
              <Typography>진행률: {selectedMission.progress}%</Typography>
              {selectedMission.childName && (
                <Typography>대상: {selectedMission.childName}</Typography>
              )}
            </Box>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDetailDialog(false)}>닫기</Button>
          {!isParent && selectedMission?.status === '진행중' && (
            <Button color="success" variant="contained" onClick={() => handleCompleteMission(selectedMission)}>
              완료하기
            </Button>
          )}
        </DialogActions>
      </Dialog>
    </Container>
  );
}

export default Missions; 