import { useState, useEffect } from 'react';
import { getMissionKingBadge } from '../utils/badgeUtils';
import { generateRandomMission } from '../utils/missionGenerator';
import {
  Box, Button, Card, CardContent, CardActions, Chip, Dialog, DialogTitle,
  DialogContent, DialogActions, TextField, Typography, LinearProgress, Alert, Paper
} from '@mui/material';
import { Add as AddIcon } from '@mui/icons-material';
import { PieChart, Pie, Cell, Tooltip as RechartTooltip, ResponsiveContainer } from 'recharts';
import { findChildById, updateChild, getChildrenByParent, updateChild as updateChildData } from '../utils/localData';
import { useLocation } from 'react-router-dom';

function Missions() {
  const location = useLocation();
  const user = JSON.parse(sessionStorage.getItem('user'));
  const isParent = user?.role === 'parent';
  const [missions, setMissions] = useState([]);
  const [openDialog, setOpenDialog] = useState(false);
  const [newMission, setNewMission] = useState({ title: '', description: '', reward: '', deadline: '' });
  const [selectedMission, setSelectedMission] = useState(null);
  const [error, setError] = useState('');
  const userId = user?.id;

  useEffect(() => {
    const hasGenerated = sessionStorage.getItem('missionAutoGenerated');
    if (!isParent && !hasGenerated && missions.length === 0) {
      const child = findChildById(user.id);
      const newMission = generateRandomMission();
      const updated = { ...child, missions: [...(child.missions || []), newMission] };
      updateChild(updated);
      setMissions(updated.missions);
      sessionStorage.setItem('missionAutoGenerated', 'true');
    }
  }, [isParent, user.id]);

  useEffect(() => {
    if (isParent) {
      const children = getChildrenByParent(userId);
      setMissions(children.flatMap(c => (c.missions || []).map(m => ({ ...m, childName: c.name, childId: c.id }))));
    } else {
      const child = findChildById(userId);
      setMissions(child?.missions || []);
    }
  }, [isParent, userId, location.pathname]);

  const handleSubmitMission = () => {
    setError('');
    if (!newMission.title || !newMission.description || !newMission.reward || !newMission.deadline) {
      setError('모든 필드를 입력해주세요.');
      return;
    }
    const children = getChildrenByParent(user.id);
    children.forEach(child => {
      const updated = { ...child };
      updated.missions = [
        ...(updated.missions || []),
        {
          id: Date.now() + Math.random(),
          ...newMission,
          progress: 0,
          status: '진행중',
          createdAt: new Date().toISOString().slice(0, 10),
        },
      ];
      updateChildData(updated);
    });
    const updatedChildren = getChildrenByParent(user.id);
    setMissions(updatedChildren.flatMap(c => (c.missions || []).map(m => ({ ...m, childName: c.name, childId: c.id }))));
    setOpenDialog(false);
    setNewMission({ title: '', description: '', reward: '', deadline: '' });
  };

  const handleRequestComplete = (mission) => {
    const child = findChildById(user.id);
    const updated = { ...child };
    updated.missions = updated.missions.map(m =>
      m.id === mission.id ? { ...m, status: '승인대기', progress: 100 } : m
    );
    updateChild(updated);
    setMissions(updated.missions);
  };

  const handleApprove = (mission) => {
    const child = findChildById(mission.childId);
    const updated = { ...child };
    updated.missions = updated.missions.map(m =>
      m.id === mission.id ? { ...m, status: '완료', progress: 100 } : m
    );
    updated.points = (updated.points || 0) + Number(mission.reward || 0);
    updateChildData(updated);
    const children = getChildrenByParent(user.id);
    setMissions(children.flatMap(c => (c.missions || []).map(m => ({ ...m, childName: c.name, childId: c.id }))));
  };

  const handleReject = (mission) => {
    const child = findChildById(mission.childId);
    const updated = { ...child };
    updated.missions = updated.missions.map(m =>
      m.id === mission.id ? { ...m, status: '거부', progress: 0 } : m
    );
    updateChildData(updated);
    const children = getChildrenByParent(user.id);
    setMissions(children.flatMap(c => (c.missions || []).map(m => ({ ...m, childName: c.name, childId: c.id }))));
  };

  const statusColor = (status) => {
    switch (status) {
      case '완료': return 'success';
      case '승인대기': return 'warning';
      case '거부': return 'error';
      default: return 'primary';
    }
  };

  const statusData = [
    { name: '완료', value: missions.filter(m => m.status === '완료').length },
    { name: '승인대기', value: missions.filter(m => m.status === '승인대기').length },
    { name: '진행중', value: missions.filter(m => m.status === '진행중').length },
    { name: '거부', value: missions.filter(m => m.status === '거부').length },
  ];

  const statusColors = {
    완료: '#4caf50',
    승인대기: '#ff9800',
    진행중: '#2196f3',
    거부: '#f44336',
  };

  return (
    <Box sx={{ maxWidth: 1200, mx: 'auto', px: 2, pt: 4 }}>
      <Typography variant="h5" fontWeight={700} sx={{ mb: 3 }}>미션 & 챌린지</Typography>

      <Paper sx={{ p: 2, mb: 4 }}>
        <Typography variant="subtitle1" gutterBottom>미션 상태 요약</Typography>
        <ResponsiveContainer width="100%" height={220}>
          <PieChart>
            <Pie
              data={statusData}
              dataKey="value"
              nameKey="name"
              cx="50%"
              cy="50%"
              outerRadius={80}
              label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
            >
              {statusData.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={statusColors[entry.name]} />
              ))}
            </Pie>
            <RechartTooltip />
          </PieChart>
        </ResponsiveContainer>
      </Paper>

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: 'repeat(5, 1fr)',
          gap: 3,
          mb: 4,
        }}
      >
        {missions.map((mission) => (
          <Card key={mission.id} sx={{ p: 2, borderRadius: 2, boxShadow: 2 }}>
            <CardContent sx={{ p: 0 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                <Typography fontWeight={600}>{mission.title}</Typography>
                <Chip label={mission.status} color={statusColor(mission.status)} size="small" />
              </Box>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>{mission.description}</Typography>
              {isParent && mission.childName && (
                <Typography variant="caption" color="text.secondary">👤 대상: {mission.childName}</Typography>
              )}
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 1 }}>
                <Typography variant="caption">💰 {mission.reward}원</Typography>
                <Typography variant="caption">📅 {mission.deadline}</Typography>
              </Box>
              <LinearProgress variant="determinate" value={mission.progress} sx={{ mt: 1, height: 6, borderRadius: 3 }} />
              <Typography variant="caption" sx={{ mt: 0.5 }}>진행률 {mission.progress}%</Typography>
            </CardContent>
            <CardActions sx={{ mt: 1, p: 0 }}>
              {!isParent && mission.status === '진행중' && (
                <Button size="small" color="primary" onClick={() => handleRequestComplete(mission)}>완료 요청</Button>
              )}
              {isParent && mission.status === '승인대기' && (
                <>
                  <Button size="small" color="success" onClick={() => handleApprove(mission)}>승인</Button>
                  <Button size="small" color="error" onClick={() => handleReject(mission)}>거부</Button>
                </>
              )}
            </CardActions>
          </Card>
        ))}
      </Box>

      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle>새 미션 만들기</DialogTitle>
        <DialogContent>
          {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
          <TextField fullWidth label="제목" margin="normal" value={newMission.title} onChange={e => setNewMission({ ...newMission, title: e.target.value })} />
          <TextField fullWidth label="설명" margin="normal" value={newMission.description} onChange={e => setNewMission({ ...newMission, description: e.target.value })} multiline rows={3} />
          <TextField fullWidth label="보상" margin="normal" type="number" value={newMission.reward} onChange={e => setNewMission({ ...newMission, reward: e.target.value })} />
          <TextField fullWidth label="마감일" margin="normal" type="date" InputLabelProps={{ shrink: true }} value={newMission.deadline} onChange={e => setNewMission({ ...newMission, deadline: e.target.value })} />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>취소</Button>
          <Button variant="contained" onClick={handleSubmitMission}>등록</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}

export default Missions;