import { useCallback, useState, useEffect } from 'react';
import { generateRandomMission } from '../utils/missionGenerator';
import {
  Box, Button, Card, CardContent, CardActions, Chip, Dialog, DialogTitle,
  DialogContent, DialogActions, TextField, Typography, LinearProgress, Alert, Paper, MenuItem
} from '@mui/material';
import { Add as AddIcon } from '@mui/icons-material';
import { PieChart, Pie, Cell, Tooltip as RechartTooltip, ResponsiveContainer } from 'recharts';
import {
  LOCAL_DATA_CHANGED_EVENT,
  findChildById,
  updateChild,
  getChildrenByParent,
  updateChild as updateChildData,
} from '../utils/localData';
import { checkAndUpdateBadges } from '../utils/badgeUtils';
import { useLocation } from 'react-router-dom';

function Missions() {
  const location = useLocation();
  const user = JSON.parse(sessionStorage.getItem('user'));
  const isParent = user?.role === 'parent';
  const [missions, setMissions] = useState([]);
  const [children, setChildren] = useState([]);
  const [openDialog, setOpenDialog] = useState(false);
  const [newMission, setNewMission] = useState({ title: '', description: '', reward: '', deadline: '' });
  const [missionTarget, setMissionTarget] = useState('all');
  const [targetChildId, setTargetChildId] = useState('');
  const [error, setError] = useState('');
  const userId = user?.id;

  const loadMissions = useCallback(() => {
    if (!userId) {
      setChildren([]);
      setMissions([]);
      return;
    }

    if (isParent) {
      const parentChildren = getChildrenByParent(userId);
      setChildren(parentChildren);
      setMissions(parentChildren.flatMap(c => (c.missions || []).map(m => ({ ...m, childName: c.name, childId: c.id }))));

      if (parentChildren.length > 0) {
        setTargetChildId(current => (
          current && parentChildren.some(child => child.id === current)
            ? current
            : parentChildren[0].id
        ));
      } else {
        setTargetChildId('');
      }
      return;
    }

    const child = findChildById(userId);
    setChildren([]);
    setMissions(child?.missions || []);
  }, [isParent, userId]);

  useEffect(() => {
    if (isParent || !userId) return;

    const child = findChildById(userId);
    if (!child || (child.missions || []).length > 0) return;

    const hasGenerated = sessionStorage.getItem(`missionAutoGenerated:${userId}`);
    if (!hasGenerated) {
      const randomMission = generateRandomMission();
      const updated = { ...child, missions: [...(child.missions || []), randomMission] };

      updateChild(updated);
      setMissions(updated.missions);
      sessionStorage.setItem(`missionAutoGenerated:${userId}`, 'true');
    }
  }, [isParent, userId]);

  useEffect(() => {
    loadMissions();
  }, [loadMissions, location.pathname]);

  useEffect(() => {
    const handleLocalDataChanged = (event) => {
      if (!event.detail?.key || event.detail.key === 'children') {
        loadMissions();
      }
    };

    const handleStorage = (event) => {
      if (!event.key || event.key === 'children') {
        loadMissions();
      }
    };

    window.addEventListener(LOCAL_DATA_CHANGED_EVENT, handleLocalDataChanged);
    window.addEventListener('storage', handleStorage);

    return () => {
      window.removeEventListener(LOCAL_DATA_CHANGED_EVENT, handleLocalDataChanged);
      window.removeEventListener('storage', handleStorage);
    };
  }, [loadMissions]);

  const handleSubmitMission = () => {
    setError('');
    if (!newMission.title || !newMission.description || !newMission.reward || !newMission.deadline) {
      setError('모든 필드를 입력해주세요.');
      return;
    }

    if (!isParent) {
      setError('미션 추가는 부모 계정에서만 가능합니다.');
      return;
    }

    const mission = {
      id: Date.now() + Math.random(),
      ...newMission,
      reward: Number(newMission.reward),
      progress: 0,
      status: '진행중',
      createdAt: new Date().toISOString().slice(0, 10),
    };

    const parentChildren = getChildrenByParent(user.id);

    if (parentChildren.length === 0) {
      setError('미션을 받을 자녀가 없습니다.');
      return;
    }

    const targetChildren = missionTarget === 'all'
      ? parentChildren
      : parentChildren.filter(child => child.id === targetChildId);

    if (targetChildren.length === 0) {
      setError('미션을 받을 자녀를 선택해주세요.');
      return;
    }

    targetChildren.forEach(child => {
      const updated = {
        ...child,
        missions: [...(child.missions || []), { ...mission, id: Date.now() + Math.random() }],
      };
      updateChildData(updated);
    });

    loadMissions();
    setOpenDialog(false);
    setNewMission({ title: '', description: '', reward: '', deadline: '' });
    setMissionTarget('all');
  };

  const handleRequestComplete = (mission) => {
    const child = findChildById(user.id);
    const updated = { ...child };
    updated.missions = updated.missions.map(m =>
      m.id === mission.id ? { ...m, status: '승인대기', progress: 100 } : m
    );
    updateChild(updated);
    loadMissions();
  };

  const handleApprove = (mission) => {
    const child = findChildById(mission.childId);
    const updated = { ...child };
    const today = new Date().toISOString().slice(0, 10);
    updated.missions = updated.missions.map(m =>
      m.id === mission.id ? { ...m, status: '완료', progress: 100, completedAt: today } : m
    );
    updated.points = (updated.points || 0) + Number(mission.reward || 0);
    checkAndUpdateBadges(updated);
    loadMissions();
  };

  const handleReject = (mission) => {
    const child = findChildById(mission.childId);
    const updated = { ...child };
    updated.missions = updated.missions.map(m =>
      m.id === mission.id ? { ...m, status: '거부', progress: 0 } : m
    );
    updateChildData(updated);
    loadMissions();
  };

  const handleRetryMission = (mission) => {
    if (isParent || !userId) return;

    const child = findChildById(userId);
    if (!child) return;

    const updated = {
      ...child,
      missions: (child.missions || []).map(m =>
        m.id === mission.id ? { ...m, status: '진행중', progress: 0 } : m
      ),
    };

    updateChild(updated);
    loadMissions();
  };

  const statusColor = (status) => {
    switch (status) {
      case '완료': return 'success';
      case '승인대기': return 'warning';
      case '거부': return 'error';
      default: return 'primary';
    }
  };

  const statusData = [
    { name: '완료', value: missions.filter(m => m.status === '완료').length },
    { name: '승인대기', value: missions.filter(m => m.status === '승인대기').length },
    { name: '진행중', value: missions.filter(m => m.status === '진행중').length },
    { name: '거부', value: missions.filter(m => m.status === '거부').length },
  ];

  const statusColors = {
    완료: '#4caf50',
    승인대기: '#ff9800',
    진행중: '#2196f3',
    거부: '#f44336',
  };

  const activeMissions = missions.filter(m => m.status === '진행중' || m.status === '승인대기');
  const completedMissions = missions.filter(m => m.status === '완료');
  const rejectedMissions = missions.filter(m => m.status === '거부');

  const renderMissionCard = (mission) => (
    <Card key={`${mission.childId || userId}-${mission.id}`} sx={{ p: 2, borderRadius: 2, boxShadow: 2 }}>
      <CardContent sx={{ p: 0 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', gap: 1, mb: 1 }}>
          <Typography fontWeight={600}>{mission.title}</Typography>
          <Chip label={mission.status} color={statusColor(mission.status)} size="small" />
        </Box>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>{mission.description}</Typography>
        {isParent && mission.childName && (
          <Typography variant="caption" color="text.secondary">👤 대상: {mission.childName}</Typography>
        )}
        <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 1 }}>
          <Typography variant="caption">💰 {mission.reward}원</Typography>
          <Typography variant="caption">📅 {mission.deadline}</Typography>
        </Box>
        <LinearProgress
          variant="determinate"
          value={mission.progress || 0}
          sx={{ mt: 1, height: 6, borderRadius: 3 }}
        />
        <Typography variant="caption" sx={{ mt: 0.5 }}>진행률 {mission.progress || 0}%</Typography>
      </CardContent>
      <CardActions sx={{ mt: 1, p: 0 }}>
        {!isParent && mission.status === '진행중' && (
          <Button size="small" color="primary" onClick={() => handleRequestComplete(mission)}>완료 요청</Button>
        )}
        {!isParent && mission.status === '거부' && (
          <Button size="small" color="primary" onClick={() => handleRetryMission(mission)}>다시 하기</Button>
        )}
        {isParent && mission.status === '승인대기' && (
          <>
            <Button size="small" color="success" onClick={() => handleApprove(mission)}>승인</Button>
            <Button size="small" color="error" onClick={() => handleReject(mission)}>거부</Button>
          </>
        )}
      </CardActions>
    </Card>
  );

  const renderMissionSection = (title, missionList, emptyText) => (
    <Paper sx={{ p: 2, mb: 4 }}>
      <Typography variant="h6" fontWeight={700} sx={{ mb: 2 }}>
        {title} ({missionList.length})
      </Typography>
      {missionList.length === 0 ? (
        <Typography color="text.secondary">{emptyText}</Typography>
      ) : (
        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: {
              xs: '1fr',
              sm: 'repeat(2, 1fr)',
              md: 'repeat(3, 1fr)',
              lg: 'repeat(4, 1fr)',
            },
            gap: 3,
          }}
        >
          {missionList.map(renderMissionCard)}
        </Box>
      )}
    </Paper>
  );

  return (
    <Box sx={{ maxWidth: 1200, mx: 'auto', px: 2, pt: { xs: '88px', sm: '96px' } }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 2, mb: 3 }}>
        <Typography variant="h5" fontWeight={700}>미션 & 챌린지</Typography>
        {isParent && (
          <Button
            variant="contained"
            startIcon={<AddIcon />}
            onClick={() => {
              setError('');
              setOpenDialog(true);
            }}
          >
            미션 추가
          </Button>
        )}
      </Box>

      <Paper sx={{ p: 2, mb: 4 }}>
        <Typography variant="subtitle1" gutterBottom>미션 상태 요약</Typography>
        <ResponsiveContainer width="100%" height={220}>
          <PieChart>
            <Pie
              data={statusData}
              dataKey="value"
              nameKey="name"
              cx="50%"
              cy="50%"
              outerRadius={80}
              label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
            >
              {statusData.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={statusColors[entry.name]} />
              ))}
            </Pie>
            <RechartTooltip />
          </PieChart>
        </ResponsiveContainer>
      </Paper>

      {renderMissionSection('진행중인 미션', activeMissions, '진행중인 미션이 없습니다.')}
      {renderMissionSection('완료한 미션', completedMissions, '완료한 미션이 없습니다.')}
      {renderMissionSection('거절된 미션', rejectedMissions, '거절된 미션이 없습니다.')}

      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle>자녀 미션 만들기</DialogTitle>
        <DialogContent>
          {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
          <TextField
            fullWidth
            select
            label="대상"
            margin="normal"
            value={missionTarget}
            onChange={e => setMissionTarget(e.target.value)}
          >
            <MenuItem value="all">전체 자녀</MenuItem>
            <MenuItem value="one">자녀 1명 선택</MenuItem>
          </TextField>
          {missionTarget === 'one' && (
            <TextField
              fullWidth
              select
              label="자녀"
              margin="normal"
              value={targetChildId}
              onChange={e => setTargetChildId(e.target.value)}
            >
              {children.map(child => (
                <MenuItem key={child.id} value={child.id}>{child.name}</MenuItem>
              ))}
            </TextField>
          )}
          <TextField fullWidth label="제목" margin="normal" value={newMission.title} onChange={e => setNewMission({ ...newMission, title: e.target.value })} />
          <TextField fullWidth label="설명" margin="normal" value={newMission.description} onChange={e => setNewMission({ ...newMission, description: e.target.value })} multiline rows={3} />
          <TextField fullWidth label="보상" margin="normal" type="number" value={newMission.reward} onChange={e => setNewMission({ ...newMission, reward: e.target.value })} />
          <TextField fullWidth label="마감일" margin="normal" type="date" InputLabelProps={{ shrink: true }} value={newMission.deadline} onChange={e => setNewMission({ ...newMission, deadline: e.target.value })} />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>취소</Button>
          <Button variant="contained" onClick={handleSubmitMission}>등록</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}

export default Missions;
